# This is a basic workflow to help you get started with Actions

name: Build Ansible CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  vagrant-up:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Copy files to /vagrant folder
      #   run: |
      #     sudo mkdir /vagrant && sudo cp -rf ./* /vagrant      

      # - name: Install python & ansible
      #   run: |      
      #     sudo apt-get update -y && sudo apt-get install -y python3.8-venv python3-pip jq unzip
      #     pip3 -q install ansible==2.10.7

      # - name: Run Ansible file
      #   run: |      
      #     sh /vagrant/provision/install-all.sh

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Install virtualbox & vagrant
        run: |      
          sudo apt-get update -y && sudo apt-get install -y virtualbox vagrant
          pip3 -q install ansible==2.10.7

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      # - name: ssh into box after boot
      #   run: vagrant ssh -c "echo 'hello world!'"

