# This is a basic workflow to help you get started with Actions

name: Build Ansible CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  vagrant-up:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install python & ansible
        run: |      
          apt-get update -y && apt-get install -y python3.8-venv python3-pip jq unzip
          pip3 -q install ansible==2.10.7

      - name: Install virtualbox & vagrant
        run: |      
          apt-get update -y && apt-get install -y virtualbox vagrant
          pip3 -q install ansible==2.10.7

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"

      # - name: ansible-lint
      #   # You may pin to the exact commit or the version.
      #   # uses: ansible/ansible-lint-action@f8608f547bbe585e82634c54859e170c39384aa4
      #   uses: ansible/ansible-lint-action@v4.1.0
      # - name: Vagrant-VirtualBox-with-repos-Vagrantfile
      #   # You may pin to the exact commit or the version.
      #   # uses: kentahikaru/github-action-vagrant--vagrantfile-from-repository@3f86c3ef7e6e7b639dc0a4aed330337d1c653793
      #   uses: kentahikaru/github-action-vagrant--vagrantfile-from-repository@v1
      #   with:
      #     # the commands to run in vm
      #     run: vagrant init && vagrant up --provision-with all
      # Runs a single command using the runners shell


      # - name: Ansible CLI
      #   # You may pin to the exact commit or the version.
      #   # uses: tomasnorre/ansible-cli-client@bd08e0a19b445d0a2bc42877fdd7a2e9d632e8e3
      #   uses: tomasnorre/ansible-cli-client@0.0.2
      #   with:
      #     # Command to execute
      #     command: ansible-playbook --connection=ssh --timeout=30 ./playbooks/provision-all.yml # default is ansible-playbook
    
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
